terms:
  - id: Audio
    term: Audio
  - id: Bound Volume
    term: Bound Volume
  - id: Dataset
    term: Dataset
  - id: Document
    term: Document
  - id: Image
    term: Image
  - id: Map
    term: Map
  - id: Mixed Materials
    term: Mixed Materials
  - id: Pamphlet
    term: Pamphlet
  - id: Periodical
    term: Periodical
  - id: Slides
    term: Slides
  - id: Video
    term: Video
  - id: Other
    term: Other
